# render.yaml
services:
  - type: web
    name: nightmonopoly-py
    region: frankfurt
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    env: python