# render.yaml
services:
  - type: web
    name: nightmonopoly-py
    region: frankfurt
    plan: free
    runtime: python
    rootDir: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nightmonopoly-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
        generateValue: true
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    env: python
    disk:
      name: nightmonopoly-db-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

databases:
  - name: nightmonopoly-db
    plan: free
    region: frankfurt