services:
  - type: web
    name: nightmonopoly-py
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    disk:
      name: nightmonopoly-data
      mountPath: /opt/render/project/src/data