services:
  - type: web
    name: nightmonopoly-py
    runtime: python
    env: python
    region: oregon
    plan: free
    envVars:
      - key: SECRET_KEY
        value: your-super-secret-key-change-it
      - key: FLASK_ENV
        value: production
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    disk:
      name: nightmonopoly-data
      mountPath: /opt/render/project/src/data