services:
  - type: web
    name: nightfanta-py
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    disk:
      name: nightfanta-data
      mountPath: /opt/render/project/src/data